### ISSUE TITLE
Problems 1 to 10

### ISSUE THREAD

**Issue by Kryptos-FR** [Color-Rise/chainblocks-euler#5]
Implement at least one solution for problems **1** through **10** with an accompanying documentation page.

- [x] Problem 1: Multiples of 3 or 5 (#1)
- [x] Problem 2: Even Fibonacci numbers (#1)
- [x] Problem 3: Largest prime factor (#1)
- [x] Problem 4: Largest palindrome product (#1)
- [x] Problem 5: Smallest multiple (#1)
- [x] Problem 6: Sum square difference (#1)
- [x] Problem 7: 10001st prime (#1)
- [x] Problem 8: Largest product in a series (#15)
- [x] Problem 9: Special Pythagorean triplet (#1)
- [x] Problem 10: Summation of primes (#1)
